name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [nightly]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.toolchain }}
        override: true
        components: clippy
    - name: Install Honggfuzz dependencies
      run: sudo apt install build-essential binutils-dev libunwind-dev libblocksruntime-dev liblzma-dev
    - name: Install Honggfuzz
      run: cargo install honggfuzz
    - name: Build
      run: cargo build --lib --verbose
    - name: Build Honggfuzz targets
      run: cargo hfuzz build --verbose
    - name: Build Honggfuzz targets in debug mode
      run: cargo hfuzz build-debug --verbose
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings -D clippy::pedantic
